### ISSUE TITLE
Develop validate-bundle script for Validation performance improvements using parallelization approach

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#128]

**Comment by rchenatjpl** [comment]
I think it'd be reasonable to ignore both these:
1) pds-int has 1 CPU and 1 core (my mac has 1 and 6 or 8 or 12 or something), so:
% validate-bundle ...
[snip...]
  Number of effective cores on this system: 1
  Half of effective cores on this system  : 0 (usually better than running all cores)
  Splitting up into groups, based on number of cores this machine has...
  Total number of products found to validate: 18
  Cleaning up files from previous runs...
/somepath/validate-bundle: line 148: (18/0)+1: division by 0 (error token is ")+1")
  Splitting up inputs into 0 groups...
    ( files per group)
  +--------------------+----------------+
  |       Group        |   # in Group   |
  +--------------------+----------------+
split: validate_all_files.txt: invalid number of lines
Try 'split --help' for more information.
[snip...]
2) On my mac, I installed parallel via `brew install parallel`rather than https://www.gnu.org/software/parallel/ (which
https://nasa-pds.github.io/validate/operate/index.html points to) because the only macos installation I see requires FINK, and I don't want another package.
