### ISSUE TITLE
As a user, I want to validate content for all possible PDS4 table types

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#217]
**Is your feature request related to a problem? Please describe.**
Right now, Validate only handles a subset of table types, but we need to make sure we check all possible objects.

This is a follow-on to #149 

See **referenced from** section under each of these for the classes we need examples and test cases for.

- [x] Table Character - https://pds.nasa.gov/datastandards/documents/im/v1/index_1D00.html#9.37%C2%A0%C2%A0class_pds_table_character
    - File_Area_Ancillary
    - File_Area_Browse
    - File_Area_Metadata
    - File_Area_Observational
    - File_Area_Observational_Supplemental
    - File_Area_Update

- [x] Transfer Manifests - https://pds.nasa.gov/datastandards/documents/im/v1/index_1D00.html#class_pds_transfer_manifest
- File_Area_Transfer_Manifest

- [x] Table Binary - https://pds.nasa.gov/datastandards/documents/im/v1/index_1D00.html#class_pds_table_binary
    - File_Area_Ancillary
    - File_Area_Browse
    - File_Area_Observational
    - File_Area_Observational_Supplemental

- [x] Table Delimited - https://pds.nasa.gov/datastandards/documents/im/v1/index_1D00.html#class_pds_table_delimited
    - File_Area_Ancillary
    - File_Area_Browse
    - File_Area_Metadata
    - File_Area_Observational
    - File_Area_Observational_Supplemental
    - File_Area_Update

**Comment by rchenatjpl** [comment]
Here are test files. In each set of 3, the ones with records=2 or 4 should fail while the one with records=2 should pass. Filenames: XXXYYYN.xml, where
XXX =
  asc: Table_Character
  tra: Transfer_Manifest
  bin: Table_Binary
  del: Table_Delimited
YYY =
  anc: File_Area_Ancillary
  bro: File_Area_Browse
  met: File_Area_Metadata
  obs: File_Area_Observational
  sup: File_Area_Observational_Supplemental
  upd: File_Area_Update 
  inv: File_Area_Inventory
N = value of <records>. All data files have 3 records

These cases are covered, based on Jordan's IM list:
  Table Character: anc bro met obs sup
  Table Binary: anc bro obs sup
  Table Delimited: anc bro met obs sub inv

Not covered: XXXsupN because File_Area_Update is deprecated
Not covered: traYYYN. Does someone have a sample? I don't work with NSSDC
Not covered: the IM does not mention Table_Delimited_Source_Product_External or Table_Delimited_Source_Product_Internal, but the .xsd does

[val217.zip](https://github.com/NASA-PDS-Incubator/validate/files/4495738/val217.zip)

**Comment by al-niessner** [comment]
@jordanpadams @rchenatjpl 

This has been a few years waiting. It looks to already be fixed but want to make sure I understand the test data and expectations. It seems like records 2 and 3 pass because the table is smaller or equal to what is there while records of 4 fail. Is this the correct expectation?

**Comment by jordanpadams** [comment]
> Here are test files. In each set of 3, the ones with records=2 or 4 should fail while the one with records=2 should pass.

@rchenatjpl just to verify, should this say:
> the ones with records=2 or 3 should fail while the one with **records=4 should pass**.

**Comment by rchenatjpl** [comment]
@jordanpadams You're right. Boy, this is like software anthropology.

**Comment by jordanpadams** [comment]
@al-niessner per above, that is correct. if those tests are implemented in the PR then we should be good to go

**Comment by jordanpadams** [comment]
closed per https://github.com/NASA-PDS/validate/pull/640
