### ISSUE TITLE
Revert record counter checks for data after the label specifies

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#236]
Several issues over the past month have been included to make updates to the counting of records in a table.

When making these updates, we also began throwing a warning when we "thought" the data may be going beyond what was specified in the label. However, after discussing with EN Team, we have decided to rollback those changes, and require that the label specify a "footer" if it is exists. Otherwise, validate will have to assume any erroneous data after the last record is expected and valid.

**Comment by msbentley** [comment]
Thanks @jordanpadams - I have a few questions:

1. How will this be implemented in labels, using the Header class, or will there be a change to the IM? 

2. To understand, this will require that a "footer" be placed between tables in the case that there are extra bytes, and after a table if there is extra space. But not before?

3. This is only for Table_*, right? This does not affect e.g. arrays which have extra chaff amongst the wheat?

4. Will this throw an error and fail validation? If so, will a switch be included to disable it? Otherwise this will start to reject perfectly good products (according to the IM) until we can get our teams to update their products.

Thanks!

**Comment by jordanpadams** [comment]
Related tickets that need to be re-tested / closed as wontfix/duplicate:
* #149 - i think this may have been the starter
* #219 - performance fix per #149 
* #220 - bug from #149 
* #233 
* #234 


Other fixes that may be impacted:
* #209 - need to make sure this fix is still valid

**Comment by jordanpadams** [comment]
@msbentley sorry for the delay here. after looking back through this, we actually do have some bugs that need to be addressed for when the number of records in the data file are shorter than what is specified in the label, for when the number of records is longer, we are just going to ignore those for now. if it is determined to be something we should check with validate, we can bring it to the DDWG to define some "footer" data object to be added to File_Area_Observational

**Comment by msbentley** [comment]
Thanks @jordanpadams. So we'll wait for the discussion with the DDWG for the footer object etc. I could imagine this could open a broader discussion on un-labelled bits and byte in products!

Will there be a flag to disable the incorrect warnings on table lengths?

**Comment by jordanpadams** [comment]
@msbentley we will no longer check if tables are too long. however, if the tables are short (e.g. label says 20 records but there are only 18) there will not be a flag because that is an invalid table
