### ISSUE TITLE
Update context check to retrieve and use latest context products from EN Registry

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#24]
The context reference validation feature that has been added to Validate Tool is just a short term solution. I think in the long run, we will want to go out to the EN Registry to find the latest context products.

Basically there would be an additional class / method added to the Validate source to perform this remote check of the EN Registry.

I would think it should replace the JSON file that comes with the delivered software (backup the old version), that way if they do not have an internet connection, it will validate with the latest based upon when the user last ran the tool.

Requirements: Add a `-u`, update,  flag that forces the tool to try to download the latest set of context products (and replace the existing file).

See also closed pull request on private repo: https://github.jpl.nasa.gov/PDSEN/pds4-java/pull/114

**Comment by msbentley** [comment]
The remote update will be great! However, in the PSA we will for sure have context targets that are not yet registered with PDS, and because of our use of the "operational archive" strategy (daily ingestions), we may be blocked from ingesting data unless we can have an option to include a set of "local" context products.

So I guess from our side we would want a method to append to the list retrieved from the registry with a local list. This could be from a json, or potentially even from a server on our side.

Or is there a more clever way to address this issue?

**Comment by jordanpadams** [comment]
@msbentley see #28 . there may be a more robust solution, but I think that should meet your needs for the time being? we will add this to our list of tasks

**Comment by msbentley** [comment]
Perfect, thanks!
