### ISSUE TITLE
validate misses double quotes within a delimited table

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/validate#298]
Line 5 of the attached .csv has
  1998_1228,1998_1228-0,"The data sets consist of (1) three small ""photometric spot"" sub-framed ...

That is illegal based on the PDS4 Standards, section 4C.1, bullet 6:
  Fields may optionally be bracketed by a pair of bounding double quotes... If bracketing double quotes are used, there may be no double quotes within the field itself.

validate passes the file with no errors. PDS4 viewer correctly chokes on it.
[Archive.zip](https://github.com/NASA-PDS/validate/files/5998735/Archive.zip)

**Comment by jordanpadams** [comment]
Some info from @qchaupds 

How to parse a comma delimited field for double quotes.

Due to the fact that the standard reference document making exception that a comma delimited field can start with a double quote, splitting a line into individual tokens using comma is not that straight forward.  Simply using line.split(",") will produce false tokens if the field contains a comma between two double quotes.


For example this line:

1998_1803,1998_1803-3,"Similar ratios ""Yogi"" soils and ""Mermaid"", but are far."

The 3rd column starts with "Similar ratios " and then contains ""Yogi"" but also had a comma after ""Mermaid"" and then finally end with far."

So if a field start with a double quote, read until the last double quote.

The Java code must do this before the class that translate a line into a record because:

Any information about how a field starts (with double quote) or not is lost.
The starting and ending double quote is removed from the content of the field.
The class that parses a line into a record also magically change two double quotes into one double quote.  Someone must of designed it that way for a reason.

A boolean array is kept for each line if each column starts with a double quotes or not for later used by the class that performs the validation of a field.  That validator can then check if a field starts with a double quote also contains another double quote for the violation of this issue.

The code is finally working correctly today reporting the offending records:

      "status": "FAIL",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github298/invalid/sentences.xml",
      "messages": [],
      "fragments": [],
      "dataContents": [
        {
          "dataFile": "file:/home/qchau/sandbox/validate/src/test/resources/github298/invalid/sentences.csv",
          "messages": [
            {
              "severity": "ERROR",
              "type": "error.validation.invalid_field_value",
              "table": 1,
              "record": 2,
              "field": 3,
              "message": "The field value 'This line should be invalid because it has \"double quote inside double quote\" and some token' that starts with double quote should not contain double quote(s)"
            },
            {
              "severity": "ERROR",
              "type": "error.validation.invalid_field_value",
              "table": 1,
              "record": 5,
              "field": 3,
              "message": "The field value 'The data sets consist of (1) three small \"photometric spot\" sub-framed (64x64 pixel) scenes located approximately north (near the rock \"Shaggy\"), south (near the \"Mermaid Dune\"), and west of the lander (\"Photometry Flats\"), (2) two image strips composed of three sub-framed (96x248 pixel) images each, located along the anti-sunrise and anti-sunset lines (\"Photometric equator\") extending from near the lander to near the horizon; and (3) full-image scenes of the rock \"Yogi.' that starts with double quote should not contain double quote(s)"
            },

The work horse of creating a boolean array is done in TabulatedUtil.java class and is then made available to FieldValueValidator.java class.

**Comment by jordanpadams** [comment]
@rchenatjpl FYI, I really think this should be updated in the PDS DSV standard. This is completely contrary to the definition the actual CSV format standard, https://www.ietf.org/rfc/rfc4180.txt:

```
   7.  If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.  For example:

       "aaa","b""bb","ccc"
```

**Comment by rchenatjpl** [comment]
That's fine with me. 1) Besides getting Ron and/or Steve to rewrite the standards, do you also want to include the SBN UMD people, whose PDS4 Viewer handles these quotes based on our standards? 2) Do you want me to say something to Scott Vanbommel and Kiri Wagstaff, whose labels started this?

**Comment by jordanpadams** [comment]
@rchenatjpl (1a) I pinged Ron and Steve via email.
(1b) per SBN, does PDS4 Viewer throw an error when trying to read this? Or does it not care? This seems like a super fine nuance within the PDS4 standard, but maybe Python libraries handle it more cleanly.
(2) i'm not sure we need to ping Scott/Kiri just yet. i imagine they output that file using some common writer.

In the end, my recommendation would be to follow the CSV format standard above, or only allow double quotes to enclose a field, period. The way this is written seems more complicated than it needs to be?

**Comment by rchenatjpl** [comment]
Sorry, I forgot about this. Yes, PDS4 Viewer chokes on the "", while validate doesn't care. 
% diff sentences[34].csv
4a5
> 1998_1228,1998_1228-0,"The data sets consist of (1) three small ""photometric spot"" sub-framed (64x64 pixel) scenes located approximately north (near the rock ""Shaggy""), south (near the ""Mermaid Dune""), and west of the lander (""Photometry Flats""), (2) two image strips composed of three sub-framed (96x248 pixel) images each, located along the anti-sunrise and anti-sunset lines (""Photometric equator"") extending from near the lander to near the horizon; and (3) full-image scenes of the rock ""Yogi."
[sentences.zip](https://github.com/NASA-PDS/validate/files/6106015/sentences.zip)
<img width="723" alt="sentences3" src="https://user-images.githubusercontent.com/56557532/110422051-7ea02f00-8053-11eb-9f97-9efef8f8a284.png">
<img width="706" alt="sentences4" src="https://user-images.githubusercontent.com/56557532/110422056-8069f280-8053-11eb-8f03-51182e675ac5.png">

**Comment by jordanpadams** [comment]
thanks @rchenatjpl . looks like they implemented a custom CSV parser in PDS4Viewer, while we tried to lean on a CSV parser written to the RFC CSV specification. what were we thinking :-)

**Comment by jordanpadams** [comment]
status: ticket is and PR are tabled for time being until we can figure out the best route to address this issue

**Comment by wkiri** [comment]
@jordanpadams I am just seeing this ticket now.  We reported this issue to Scott VanBommel last year, when the validate tool generates an error for internally nested double-quotes.  As you noted, the PDS standard says it is based on RFC 4180, which states:
>  If double-quotes are used to enclose fields, then a double-quote
>  appearing inside a field must be escaped by preceding it with
>  another double quote. 

Comments above suggest that validate allows "", but that is not my experience.  Here is the output from validate 2.1.4, when we encode it as ""allophane"":
>      ERROR  [error.validation.invalid_field_value]   table 1, record 1, field 3: The field value 'The four "allophane" and gel spectra were added to spectral libraries used to model Mini-TES spectra of fresh and altered rocks from Gusev (Adirondack, Clovis, Wishstone, and Watchtower) [16].' that starts with double quote should not contain double quote(s) 

I suspect that validate may be reading in the content (a typical CSV reader will convert "" back to ") and *then* checking for the existed of a double-quote.  I don't think the existence of a double-quote should be invalid.

To make validate happy, we have been either:
(1) post-processing CSV content to convert internal "" (as written by the Pandas CSV writer) to ''
(2) pre-processing strings to convert " to '' before writing to CSV
Neither one is a great solution.  What do you recommend?

**Comment by jordanpadams** [comment]
@wkiri apologies if the comments above are misleading, but `Comments above suggest that validate allows ""` is not correct. The PDS DSV is "based on RFC 4180", but not exactly. Here is the specific bullet in question:
<img width="672" alt="Screen Shot 2022-02-11 at 7 57 17 PM" src="https://user-images.githubusercontent.com/33492486/153694070-e5631661-4a66-4a61-85c7-26ad833a6ef6.png">

Note this sentence:
>   If  bracketing double  quotes  are  used, there  may  be  no double  quotes  within the  field itself. 

We actually had to a fork the CSV library we were using in order to customize it for the PDS DSV: https://github.com/NASA-PDS/pds-opencsv

I agree that the pre-processing is not ideal, but this is how the standard was written. If you feel this should not be the case, I would work with @myche and IMG to submit an SCR to have this changed.

**Comment by jordanpadams** [comment]
@wkiri also thanks for following up here, I created a discussion thread on this topic as well since I imagine you aren't the first person to encounter this: https://github.com/NASA-PDS/validate/discussions/478

**Comment by wkiri** [comment]
Thanks, @jordanpadams !  Earlier it was stated that "validate passes the file with no errors" but that is not my experience.  However, maybe this was an earlier version of validate, and your most recent updates now trigger the error.  I'm sorry to hear that you had to work around this specification too.  Thanks for the suggestion to consider an SCR.

**Comment by jordanpadams** [comment]
@wkiri gotcha! Yeah the original bug was because validate accepted it, but per the spec, it shouldn't. So now it throws the error as expected.
