### ISSUE TITLE
include failing file(s) in validate_stack_traces.log

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/validate#313]
File validate_stack_traces.log should say what file caused the error. This is a problem when validating a bundle with many files. If it's impossible to do that, I suggest removing this functionality, since `validate ... >& log` would be better though not ideal either.

validate also left file validate_stack_traces.log.temp in the directory I ran in. That's bad.

### Engineering Details
- [ ] add to stacktrace the file where it fails (if possible)

**Comment by rchenatjpl** [comment]
[Archive.zip](https://github.com/NASA-PDS/validate/files/6200081/Archive.zip)

**Comment by jordanpadams** [comment]
@rchenatjpl we will add in the file where it fails. we try to catch as many exceptions as possible in code because we get a lot of complaints from users when they see stacktraces in output reports.

**Comment by qchaupds** [comment]
Just my initial thoughts: Often times when something fails, the code that is encountering the exception does not know what file it is working on because of the design of the function.  As Jordan had pointed out, the initial reason for the file is to steer the output from console to an external file (for developer first and perhaps helpful to the user).

Will look at this issue next week and may have more comments.

**Comment by jordanpadams** [comment]
@rchenatjpl per some discussions, we are going to close this as `wontfix`. the stack trace is really for the developer on a failure. if a user has one of these critical failures, we hope they just file a bug and we can use that stacktrace to help debug.
