### ISSUE TITLE
File-size check fails for large data files

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS/validate#326]
## 🐛 Describe the bug
Trying to validate a large product, but skipping data validation, the new file size check (label vs actual file size) apparantly fails when the data file is too large, with the error:

```
ERROR  [error.label.filesize_mismatch]   Generated filesize '-1' does not match supplied filesize '5060141280' in the product label for 'file:/home/mbentley/Desktop/dictionary_test/mertis/mer_raw_sc_tis_20201214_4_table.dat'
```
As you can see the file in question is quite large (4.8GB).

## 📜 To Reproduce
1. Try to validate a large data file with validate 2.0.2

## 🕵️ Expected behavior
File-size checks do not fail for large files ;-)

## 📚 Version of Software Used
Version 2.0.2

## 🖥 System Info
 - OS: linux, ubuntu, 20.04

---

** :unicorn: Applicable requirements**

**Comment by qchaupds** [comment]
@msbentley Hi Mark, with some small changes in validate module, we were able to validate a very large file (with the --skip-content-validation flag)

{pds-dev3.jpl.nasa.gov}/data/home/pds4/qchau/test_artifacts/github326 132 % ls -lctr
total 4194320
-rw-r--r-- 1 qchau pds        405 Apr 21 09:17 spectra_data_collection_inventory.csv
-rw-r--r-- 1 qchau pds 4294967296 Apr 21 09:18 gentoo_root.csv
-rw-r--r-- 1 qchau pds 4294967701 Apr 21 09:20 very_large_file.csv
-rw-r--r-- 1 qchau pds       4490 Apr 21 09:22 spectra_data_collection_inventory.xml

The file very_large_file.csv was created by combining the spectra_data_collection_inventory.csv with 5 records and the large file gentoo_root.csv.   We can test the file_size validation but not the content since validate would fail with such a large file.

{pds-dev3.jpl.nasa.gov}/data/home/pds4/qchau/test_artifacts/github326 136 % egrep "file_name|file_size" spectra_data_collection_inventory.xml
      <file_name>very_large_file.csv</file_name>
      <file_size unit="byte">4294967701</file_size>


{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 131 % validate -R pds4.label --skip-content-validation --skip-context-validation -r report_github326_label_valid.json -s json -t /data/home/pds4/qchau/test_artifacts/github326/spectra_data_collection_inventory.xml

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 130 % egrep "label|status"  report_github326_label_valid.json
    "ruleType": "pds4.label",
      "status": "PASS",
      "label": "file:/data/home/pds4/qchau/test_artifacts/github326/spectra_data_collection_inventory.xml",

The changes will be pushed to a working branch at the next opportunity.

**Comment by jordanpadams** [comment]
@qchaupds does it work without the `--skip-content-validation` flag?

**Comment by qchaupds** [comment]
It does not work without the --skip-content-validation flag.   Validate runs out of memory while reading the file:

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 146 %validate -R pds4.label --skip-context-validation -r report_github326_label_valid_without_skip.json -s json -t /data/home/pds4/qchau/test_artifacts/github326/spectra_data_collection_inventory.xml > & t3

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 145 % tail -60 report_github326_label_valid_without_skip.json
{
  "title": "PDS Validation Tool Report",
  "configuration": {
    "version": "1.25.0-SNAPSHOT",
    "date": "2021-04-21T21:59:06Z"
  },
  "parameters": {
    "targets": "[file:/data/home/pds4/qchau/test_artifacts/github326/spectra_data_collection_inventory.xml]",
    "ruleType": "pds4.label",
    "severityLevel": "WARNING",
    "recurseDirectories": "true",
    "fileFiltersUsed": "[*.xml, *.XML]",
    "dataContentValidation": "on",
    "productLevelValidation": "on",
    "maxErrors": "100000",
    "registeredContextsFile": "src/main/resources/util/registered_context_products.json"
  },
  "productLevelValidationResults": [
    {
      "status": "FAIL",
      "label": "file:/data/home/pds4/qchau/test_artifacts/github326/spectra_data_collection_inventory.xml",
      "messages": [
        {
          "severity": "ERROR",
          "type": "error.label.filesize_mismatch",
          "message": "Generated filesize '-1' does not match supplied filesize '4294967701' in the product label for 'file:/data/home/pds4/qchau/test_artifacts/github326/very_large_file.csv'"
        },
        {
          "severity": "ERROR",
          "type": "error.validation.internal_error",
          "message": "Error executing validationTask: java.lang.OutOfMemoryError: Java heap space"
        }
      ],
      "fragments": [],
      "dataContents": []
    }
  ],
  "summary": {
    "totalErrors": 2,
    "totalWarnings": 0,
    "messageTypes": [
      {
        "messageType": "error.validation.internal_error",
        "total": 1
      },
      {
        "messageType": "error.label.filesize_mismatch",
        "total": 1
      }
    ]
  }
}

Inspecting the standard out, the memory runs out at:
gov.nasa.pds.objectAccess.TableReader.getRecordSize(TableReader.java:332)

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 148 % vi t3


java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:71)
    at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
    at gov.nasa.pds.tools.validate.task.ValidationTask.execute(ValidationTask.java:134)
    at gov.nasa.pds.tools.validate.task.BlockingTaskManager.submit(BlockingTaskManager.java:27)
    at gov.nasa.pds.tools.label.LocationValidator.validate(LocationValidator.java:265)
    at gov.nasa.pds.validate.ValidateLauncher.doValidation(ValidateLauncher.java:1288)
    at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1533)
    at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1579)
Caused by: java.lang.OutOfMemoryError: Java heap space
    at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
    at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
    at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:686)
    at java.base/java.lang.StringBuilder.append(StringBuilder.java:228)
    at java.base/java.io.BufferedReader.readLine(BufferedReader.java:372)
    at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
    at gov.nasa.pds.objectAccess.TableReader.getRecordSize(TableReader.java:332)
    at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.validateTableDataContents(TableDataContentValidationRule.java:296)
    ... 12 more
[main] DEBUG gov.nasa.pds.tools.util.Utility - isDir:file,url /data/home/pds4/qchau/test_artifacts/github326/spectra_data_collection_inventory.xml,file:/data/home/pds4/qchau/test_artifacts/github326/spectra_data_collection_inventory.xml
[main] DEBUG gov.nasa.pds.tools.util.Utility - isDir:ext_len,url 3,file:/data/home/pds4/qchau/test_artifacts/github326/spectra_data_collection_inventory.xml
[main] DEBUG gov.nasa.pds.tools.util.Utility - isDir:isDir(),url,file false,file:/data/home/pds4/qchau/test_artifacts/github326/spectra_data_collection_inventory.xml,/data/home/pds4/qchau/test_artifacts/github326/spectra_data_collection_inventory.xml
[main] ERROR gov.nasa.pds.tools.validate.task.ValidationTask - Unexpected exception executing validation rule

**Comment by qchaupds** [comment]
@jordanpadams Forgot to use the at symbol.  There's a comment above this one.

Short answer is NO.

**Comment by jordanpadams** [comment]
@qchaupds copy. so we will need to investigate this further. i imagine we are trying to read int all the data at once, instead of reading it in in chunks. here was the last time we tried to address these memory problems. looks like we may have to do this elsewhere in the code as well.

https://github.com/NASA-PDS/pds4-jparser/pull/31/files

**Comment by msbentley** [comment]
Hi @jordanpadams I raised a parallel ticket for the fact that the file failed to validate content: #327. Sorry, I should have explicitly linked them when creating!

**Comment by jordanpadams** [comment]
@msbentley copy that.

**Comment by qchaupds** [comment]
We have good success on validating the size and content of our 4GB test file (.csv) with the new code change.
Once we have the real test file, we can attempt to validate that as well.

**Comment by msbentley** [comment]
Hi @qchaupds OK, the file is not public, so I cannot directly share a link to it. Either I can ask permission to share it privately, or if you have a snapshot or other version of validate with the fix you can send, I can test that?

**Comment by jordanpadams** [comment]
@msbentley we will test internally with what @qchaupds has come up with and then we can see if that fixes it. Per our regression tests, it doesn't appear to break what we already have so it hopefully will be a step in the right direction.

**Comment by qchaupds** [comment]
For developer(s): The old implementation of BufferReader is problematic if the file size exceeds 2GB.  Using RandomAccessFile and FileChannel gets around the issue having to use large amount of memory from the heap.

See the functions getMD5Checksum() in src/main/java/gov/nasa/pds/tools/util/MD5Checksum.java
and countCarriageReturn() function in the pds4-jparser module of src/main/java/gov/nasa/pds/objectAccess/TableReader.java class for example of using the random class.

They are not perfect but they work for now.  May have to make some modifications to support #325.
