### ISSUE TITLE
stack trace being created during successful validate execution

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#380]
## 🐛 Describe the bug

Follow-on to #344, [this comment](https://github.com/NASA-PDS/validate/issues/344#issuecomment-888117878) and #379, the stack trace output file is causing numerous issues.

## 🕵️ Expected behavior

stack trace only outputs when a fatal error occurs or uncaught exception.

## 📚 Version of Software Used

v2.0.7

---

## ⚙️ Engineering Details
- [x] perform full scrub of validate and pds4-jparser (if necessary) to ensure every instance of the creation of a write to the stack trace is warranted.
   * this should only occur on uncaught exceptions or fatal errors

**Comment by qchaupds** [comment]
@jordanpadams Do you have a particular test case that you'd seen this behavior?  I am not able to reproduce the error you'd mentioned.

**Comment by msbentley** [comment]
Hi @jordanpadams and @qchaupds it would be good to clarify exactly what is expected. #344 discusses the generation of the log during successful validation, but from @jordanpadams's description above, I would not expect the log to be generated with validation failure - since this is not an application error, but application success ;-) 

As in that linked ticket, one simple example is to mis-name the data file referenced in the label (e.g. referenced in a Table_Delimited or other class), which results in `Error occurred while trying to read table` and a stack trace log.

**Comment by jordanpadams** [comment]
closed per #385
